[[cpp]]
profmode = "direct"
[[cpp.env]]
PROTEUS_USE_STORED_CACHE = "0"
PROTEUS_SPECIALIZE_LAUNCH_BOUNDS = "1"
PROTEUS_SPECIALIZE_ARGS = "1"
PROTEUS_SPECIALIZE_DIMS = "1"
PROTEUS_ENABLE_TIMERS = "1"


#[[cpp]]
#profmode = "metrics"
#[[cpp.env]]
#PROTEUS_USE_STORED_CACHE = "1"
#PROTEUS_SPECIALIZE_LAUNCH_BOUNDS = "1"
#PROTEUS_SPECIALIZE_ARGS = "1"
#PROTEUS_SPECIALIZE_DIMS = "1"
#PROTEUS_ENABLE_TIMERS = "1"
